### ISSUE TITLE
Assuming that no FAM is present on the bus - FTS14KS device not detected

### ISSUE THREAD

**Issue by michaelpiron** [onIon-Energy/eltako14bus#3]
Loaded this package locally in my environment, using it as part of the Eltako 14 Home Assistant custom component (https://github.com/michaelpiron/home-assistant-eltako).

Multiple errors are thrown. Here's the full log from home assistant:
```
2023-01-04 10:18:06.604 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration eltako which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-01-04 10:18:09.737 WARNING (MainThread) [root] Development mode; Using eltakobus module from /config/packages/eltako14bus/__init__.py

2023-01-04 10:22:55.561 ERROR (MainThread) [eltako]
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/packages/eltako14bus/serial.py", line 213, in exchange
return await asyncio.wait_for(match, timeout=1)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/eltako/__init__.py", line 133, in wrapped_main
await self.main(*args)
File "/config/custom_components/eltako/__init__.py", line 291, in main
await self.sweep(bus, programming)
File "/config/custom_components/eltako/__init__.py", line 271, in sweep
bus_status = await locking.unlock_bus(bus)
File "/config/packages/eltako14bus/locking.py", line 48, in unlock_bus
response = await bus.exchange(EltakoBusUnlock(), EltakoMessage)
File "/config/packages/eltako14bus/serial.py", line 218, in exchange
raise TimeoutError
eltako14bus.error.TimeoutError


2023-01-04 10:22:55.569 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback EltakoBusController.initialize_bus_task.<locals>.bus_done(<Task cancell...serial.py:97>>) at /config/custom_components/eltako/__init__.py:118
Traceback (most recent call last):
File "/config/packages/eltako14bus/serial.py", line 135, in run
await self.await_bufferlevel(14)
File "/config/packages/eltako14bus/serial.py", line 58, in await_bufferlevel
await self._buffer_request
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/config/custom_components/eltako/__init__.py", line 121, in bus_done
result = bus_future.result()
asyncio.exceptions.CancelledError

2023-01-04 10:24:37.153 ERROR (MainThread) [homeassistant.core] Error in event filter
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 922, in async_fire
if not event_filter(event):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1797, in _handle_entry_updated_filter
event.data["action"] != "update"
KeyError: 'action'

2023-01-04 10:24:37.162 ERROR (MainThread) [homeassistant.core] Error in event filter
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 922, in async_fire
if not event_filter(event):
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 992, in cleanup_restored_states_filter
return bool(event.data["action"] == "remove")
KeyError: 'action'

2023-01-04 10:24:37.167 ERROR (MainThread) [homeassistant.core] Error in event filter
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 922, in async_fire
if not event_filter(event):
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 371, in _async_entity_registry_updated_filter
entity_id = event.data.get("old_entity_id", event.data["entity_id"])
KeyError: 'entity_id'

2023-01-04 10:24:37.171 ERROR (MainThread) [homeassistant.core] Error in event filter
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 922, in async_fire
if not event_filter(event):
File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 323, in entity_registry_changed_filter
if event.data["action"] != "update" or "old_entity_id" not in event.data:
KeyError: 'action'

2023-01-04 10:24:37.177 ERROR (MainThread) [homeassistant.core] Error in event filter
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 922, in async_fire
if not event_filter(event):
File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 823, in entity_registry_changed_filter
event.data["action"] == "update"
KeyError: 'action'

2023-01-04 10:24:37.182 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/person/__init__.py", line 234, in _entity_registry_updated
if event.data["action"] != "remove":
KeyError: 'action'
```

**Comment by michaelpiron** [comment]
Got some more detailed logging out. **It seems that the FAM14 (or in my case the FTS14KS) device is not detected.**
What would be causing this?
- Should I change the rotary switch position on FTS14KS?
- Should I use a USB connection to the FTS14KS instead of USB connection to FGW14-USB?
- Is the code specifically for FAM14, not suitable for FTS14KS?

I'll figure this out further.

Log:
```
2023-01-04 16:52:10.653 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration eltako which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-04 16:52:14.536 WARNING (MainThread) [root] Development mode; Using eltakobus module from /config/packages/eltako14bus/__init__.py

2023-01-04 16:52:14.545 INFO (MainThread) [homeassistant.setup] Setting up eltako
2023-01-04 16:52:15.160 INFO (MainThread) [homeassistant.setup] Setup of domain eltako took 0.6 seconds
2023-01-04 16:52:15.163 DEBUG (MainThread) [eltako] Waiting for platforms to register
2023-01-04 16:52:15.167 INFO (MainThread) [homeassistant.components.cover] Setting up cover.eltako
2023-01-04 16:52:15.168 INFO (MainThread) [homeassistant.components.light] Setting up light.eltako
2023-01-04 16:52:15.169 INFO (MainThread) [homeassistant.components.switch] Setting up switch.eltako
2023-01-04 16:52:15.169 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.eltako
2023-01-04 16:52:15.176 DEBUG (MainThread) [eltako] Platforms registered
2023-01-04 16:52:15.188 DEBUG (MainThread) [eltako.serial] Performing echo detection
2023-01-04 16:52:15.443 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2023-01-04 16:52:18.943 DEBUG (MainThread) [eltako.serial] No echo detected on the line
2023-01-04 16:52:19.274 INFO (MainThread) [eltako] Serial device detected and ready
2023-01-04 16:52:19.274 DEBUG (MainThread) [eltako] Locking bus
2023-01-04 16:52:43.325 DEBUG (MainThread) [eltako] Bus locked (No response after 10 repetitions, assuming that no FAM is present on the bus), enumerating devices
2023-01-04 16:56:58.736 DEBUG (MainThread) [eltako] Forcing status messages from 0 known channels
2023-01-04 16:56:58.736 DEBUG (MainThread) [eltako] Unlocking bus


2023-01-04 16:56:59.738 ERROR (MainThread) [eltako]
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/packages/eltako14bus/serial.py", line 213, in exchange
return await asyncio.wait_for(match, timeout=1)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/eltako/__init__.py", line 133, in wrapped_main
await self.main(*args)
File "/config/custom_components/eltako/__init__.py", line 291, in main
await self.sweep(bus, programming)
File "/config/custom_components/eltako/__init__.py", line 271, in sweep
bus_status = await locking.unlock_bus(bus)
File "/config/packages/eltako14bus/locking.py", line 48, in unlock_bus
response = await bus.exchange(EltakoBusUnlock(), EltakoMessage)
File "/config/packages/eltako14bus/serial.py", line 218, in exchange
raise TimeoutError
eltako14bus.error.TimeoutError


2023-01-04 16:56:59.742 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback EltakoBusController.initialize_bus_task.<locals>.bus_done(<Task cancell...serial.py:97>>) at /config/custom_components/eltako/__init__.py:118
Traceback (most recent call last):
File "/config/packages/eltako14bus/serial.py", line 135, in run
await self.await_bufferlevel(14)
File "/config/packages/eltako14bus/serial.py", line 58, in await_bufferlevel
await self._buffer_request
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/config/custom_components/eltako/__init__.py", line 121, in bus_done
result = bus_future.result()
asyncio.exceptions.CancelledError
```

Things seem to be going wrong in the **sweep** function.

**Comment by michaelpiron** [comment]
Issue doesn't appear anymore since the refactoring of the homeassistant-eltako integration code -> https://github.com/michaelpiron/home-assistant-eltako/pull/6.

This issue can be closed
